# Generated by Django 4.1.1 on 2022-10-05 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=180, null=True)),
                ('description', models.CharField(blank=True, max_length=180, null=True)),
                ('imageUrl', models.CharField(blank=True, max_length=180, null=True)),
                ('pdfUrl', models.CharField(blank=True, max_length=180, null=True)),
                ('videoUrl', models.CharField(blank=True, max_length=180, null=True)),
                ('sumRate', models.CharField(blank=True, max_length=180, null=True)),
                ('rating', models.CharField(blank=True, max_length=180, null=True)),
                ('date', models.CharField(blank=True, max_length=180, null=True)),
                ('status', models.CharField(blank=True, max_length=180, null=True)),
                ('type', models.CharField(blank=True, max_length=180, null=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=180, null=True)),
                ('description', models.CharField(blank=True, max_length=180, null=True)),
                ('color', models.CharField(blank=True, max_length=180, null=True)),
                ('iconUrl', models.CharField(blank=True, max_length=180, null=True)),
                ('type', models.CharField(blank=True, max_length=180, null=True)),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'db_table': 'courses_categories',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Course Material',
                'verbose_name_plural': 'Courses Materials',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0)),
                ('materials', models.ManyToManyField(to='courses.material')),
            ],
            options={
                'verbose_name': 'Course Lesson',
                'verbose_name_plural': 'Courses Lessons',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'verbose_name': 'Featured Course',
                'verbose_name_plural': 'Featured Courses',
                'db_table': 'courses_featured',
                'ordering': ['ordering'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.RESTRICT, to='courses.coursecategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(to='courses.lesson'),
        ),
    ]
