# Generated by Django 4.1.1 on 2022-10-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_materialattachment_materialcomponent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sumRate',
        ),
        migrations.RemoveField(
            model_name='course',
            name='type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='image',
        ),
        migrations.RemoveField(
            model_name='material',
            name='content',
        ),
        migrations.AddField(
            model_name='material',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='courses.materialattachment'),
        ),
        migrations.AddField(
            model_name='material',
            name='components',
            field=models.ManyToManyField(blank=True, to='courses.materialcomponent'),
        ),
        migrations.AddField(
            model_name='materialattachment',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='materials',
            field=models.ManyToManyField(blank=True, to='courses.material'),
        ),
        migrations.DeleteModel(
            name='MaterialContent',
        ),
    ]
