# Generated by Django 4.1.1 on 2022-10-06 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_rating_remove_course_sumrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(db_column='courseId', default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
