# Generated by Django 4.1.1 on 2022-10-06 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_course_alter_course_lessons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(db_column='courseId', on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
