# Generated by Django 4.1.1 on 2022-10-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_ordering_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='courses.material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='materials', to='courses.materialattachment'),
        ),
        migrations.AlterField(
            model_name='material',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='materials', to='courses.materialcomponent'),
        ),
    ]
