# Generated by Django 4.1.1 on 2022-10-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_lesson_course_courselesson_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courselesson',
            table='_course_lesson_',
        ),
    ]
