# Generated by Django 4.1.1 on 2022-10-06 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_courselesson_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rel_Material_Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0)),
                ('component', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='courses.materialcomponent')),
                ('material', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='courses.material')),
            ],
            options={
                'db_table': '_material_component_',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Rel_Material_Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0)),
                ('attachment', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='courses.materialattachment')),
                ('material', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='courses.material')),
            ],
            options={
                'db_table': '_material_attachment_',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0)),
                ('lesson', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('material', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='courses.material')),
            ],
            options={
                'db_table': '_lesson_material_',
                'ordering': ['ordering'],
            },
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='materials',
        ),
        migrations.AddField(
            model_name='lesson',
            name='materials',
            field=models.ManyToManyField(
                blank=True, related_name='lessons', through='courses.LessonMaterial', to='courses.material'),
        ),


        migrations.RemoveField(
            model_name='material',
            name='attachments',
        ),
        migrations.AddField(
            model_name='material',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='materials',
                                         through='courses.Rel_Material_Attachment', to='courses.materialattachment'),
        ),


        migrations.RemoveField(
            model_name='material',
            name='components',
        ),
        migrations.AddField(
            model_name='material',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='materials',
                                         through='courses.Rel_Material_Component', to='courses.materialcomponent'),
        ),
    ]
