# Generated by Django 4.1.1 on 2022-10-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_rel_material_component_rel_material_attachment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseLesson',
            new_name='Rel_Course_Lesson',
        ),
        migrations.RenameModel(
            old_name='LessonMaterial',
            new_name='Rel_Lesson_Material',
        ),
    ]
