# Generated by Django 4.1.1 on 2022-10-06 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_rename_courselesson_rel_course_lesson_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rel_course_lesson',
            options={'ordering': ['ordering'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='rel_lesson_material',
            options={'ordering': ['ordering'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
        migrations.AlterModelOptions(
            name='rel_material_attachment',
            options={'ordering': ['ordering'], 'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AlterModelOptions(
            name='rel_material_component',
            options={'ordering': ['ordering'], 'verbose_name': 'Component', 'verbose_name_plural': 'Components'},
        ),
        migrations.AlterModelTable(
            name='materialattachment',
            table='courses_material_attachment',
        ),
        migrations.AlterModelTable(
            name='materialcomponent',
            table='courses_material_component',
        ),
    ]
