# Generated by Django 4.1.1 on 2022-10-06 13:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_lesson_options_alter_material_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategory',
            name='iconUrl',
        ),
        migrations.RemoveField(
            model_name='coursecategory',
            name='type',
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#C1C1C1', image_field=None, max_length=18, samples=None),
        ),
    ]
