# Generated by Django 4.1.1 on 2022-10-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_coursecategory_iconurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
