# Generated by Django 4.1.1 on 2022-10-23 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_rel_course_lesson_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rel_lesson_material',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rel_lesson_material',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='rel_lesson_material',
            name='material',
        ),
        migrations.AlterUniqueTogether(
            name='rel_material_attachment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rel_material_attachment',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='rel_material_attachment',
            name='material',
        ),
        migrations.AlterUniqueTogether(
            name='rel_material_component',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rel_material_component',
            name='component',
        ),
        migrations.RemoveField(
            model_name='rel_material_component',
            name='material',
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['ordering'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['ordering'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='material',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='material',
            name='components',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialattachment',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialcomponent',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.material'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rel_Course_Lesson',
        ),
        migrations.DeleteModel(
            name='Rel_Lesson_Material',
        ),
        migrations.DeleteModel(
            name='Rel_Material_Attachment',
        ),
        migrations.DeleteModel(
            name='Rel_Material_Component',
        ),
    ]
