# Generated by Django 4.1.1 on 2022-10-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_material_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
