# Generated by Django 4.1.1 on 2022-10-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_material_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialcomponent',
            name='material',
        ),
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MaterialAttachment',
        ),
        migrations.DeleteModel(
            name='MaterialComponent',
        ),
    ]
