# Generated by Django 4.1.1 on 2022-10-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_remove_materialcomponent_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
