# Generated by Django 4.1.1 on 2022-10-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_exam_question_questionchoice_question_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['ordering'], 'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.AddField(
            model_name='exam',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
