# Generated by Django 4.1.1 on 2022-10-27 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_exam_options_exam_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(limit_choices_to={'question__id': 'self.id'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='questions', to='courses.questionchoice'),
        ),
    ]
