# Generated by Django 4.1.1 on 2022-10-28 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='courses.exam'),
        ),
        migrations.AlterUniqueTogether(
            name='questionchoice',
            unique_together={('question', 'name')},
        ),
    ]
