# Generated by Django 4.1.1 on 2022-11-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_alter_course_category_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pdfUrl',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
