# Generated by Django 4.1.1 on 2022-11-03 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
