# Generated by Django 4.1.1 on 2022-11-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_alter_course_category_alter_coursecategory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
