# Generated by Django 4.1.1 on 2022-11-15 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_alter_course_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursecategory',
            table='course_categories',
        ),
    ]
