# Generated by Django 4.1.1 on 2022-12-02 04:16

from django.db import migrations
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_alter_coursecategory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, max_length=50, null=True),
        ),
    ]
