# Generated by Django 4.1.1 on 2022-12-07 21:42

from django.db import migrations, models
import django.db.models.deletion
import takwine.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_coursecategory_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('file', models.FileField(help_text='* Maximum upload file size 2 MB.', upload_to='files/', validators=[takwine.models.TakwineFile.file_size_validator])),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.material')),
            ],
            options={
                'verbose_name': 'Material File',
                'verbose_name_plural': 'Material Files',
                'db_table': 'material_files',
                'ordering': ['ordering'],
            },
        ),
    ]
