# Generated by Django 4.1.1 on 2022-12-13 16:47

from django.db import migrations, models
import django.db.models.deletion
import takwine.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_alter_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pdfUrl',
        ),
        migrations.AlterField(
            model_name='course',
            name='imageUrl',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='materialfile',
            name='file',
            field=models.FileField(help_text='* Maximum upload file size 5 MB.', upload_to='files/', validators=[takwine.models.TakwineFile.file_size_validator]),
        ),
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('file', models.FileField(help_text='* Maximum upload file size 5 MB.', upload_to='files/', validators=[takwine.models.TakwineFile.file_size_validator])),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
            options={
                'verbose_name': 'Course File',
                'verbose_name_plural': 'Course Files',
                'db_table': 'course_files',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='guideFile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.coursefile'),
        ),
    ]
