# Generated by Django 4.1.1 on 2022-12-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_remove_course_pdfurl_alter_course_imageurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefile',
            name='name',
            field=models.CharField(default='ملف', max_length=255),
        ),
        migrations.AlterField(
            model_name='materialfile',
            name='name',
            field=models.CharField(default='ملف', max_length=255),
        ),
    ]
