# Generated by Django 4.1.1 on 2022-11-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='imageUrl',
        ),
    ]
