# Generated by Django 4.1.1 on 2022-11-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_file_alter_documentfile_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='imageUrl',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to=''),
        ),
    ]
