# Generated by Django 4.1.1 on 2022-11-29 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='documentfile',
            name='title',
        ),
        migrations.AddField(
            model_name='documentfile',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document'),
        ),
    ]
