# Generated by Django 4.1.1 on 2022-12-07 21:29

from django.db import migrations, models
import django.db.models.deletion
import takwine.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_document_file_remove_documentfile_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcategory',
            name='color',
        ),
        migrations.AddField(
            model_name='documentfile',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document'),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(help_text='* Maximum upload file size 2 MB.', upload_to='files/', validators=[takwine.models.TakwineFile.file_size_validator]),
        ),
    ]
