# Generated by Django 4.1.1 on 2022-12-13 16:47

from django.db import migrations, models
import takwine.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_remove_documentcategory_color_documentfile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(help_text='* Maximum upload file size 5 MB.', upload_to='files/', validators=[takwine.models.TakwineFile.file_size_validator]),
        ),
    ]
