# Generated by Django 4.1.1 on 2022-12-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_documentfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='name',
            field=models.CharField(default='ملف', max_length=255),
        ),
    ]
