# Generated by Django 4.1.1 on 2022-12-13 20:32

import colorfield.fields
from django.db import migrations
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_documentfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#C1C1C1', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, max_length=50, null=True),
        ),
    ]
