# Generated by Django 4.1.1 on 2022-10-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_lesson_days'),
        ('users', '0005_alter_enrolledcourse_progress_alter_user_birthdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnrolledCourse',
            new_name='CourseProgress',
        ),
        migrations.AlterModelOptions(
            name='courseprogress',
            options={'verbose_name': 'Course Progress', 'verbose_name_plural': 'Course Progresses'},
        ),
        migrations.AlterModelTable(
            name='courseprogress',
            table='users_course_progresses',
        ),
    ]
