# Generated by Django 4.1.1 on 2022-10-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_lesson_days'),
        ('users', '0006_rename_enrolledcourse_courseprogress_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseProgress',
            new_name='Enrollment',
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='users_enrollments',
        ),
    ]
