# Generated by Django 4.1.1 on 2022-10-12 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_courseprogress_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
