# Generated by Django 4.1.1 on 2022-10-12 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_lesson_days'),
        ('users', '0009_alter_enrollment_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='progress',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='currentLesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='currentMaterial',
            field=models.ForeignKey(db_column='currentMaterialId', null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.material'),
        ),
    ]
