# Generated by Django 4.1.1 on 2022-10-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_lesson_days'),
        ('users', '0010_remove_enrollment_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='currentMaterial',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='currentMaterialId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.material'),
        ),
    ]
