# Generated by Django 4.1.1 on 2022-10-12 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_course_title'),
        ('users', '0012_remove_enrollment_currentmaterialid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='currentLesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='currentMaterial',
            field=models.ForeignKey(db_column='currentMaterialId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.material'),
        ),
    ]
