# Generated by Django 4.1.1 on 2022-10-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_course_title'),
        ('users', '0014_alter_enrollment_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
    ]
