# Generated by Django 4.1.1 on 2022-10-18 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_course_title'),
        ('users', '0015_rename_created_enrollment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rel_Enrollment_Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'db_table': '_enrollment_lesson_',
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completeLessons',
            field=models.ManyToManyField(blank=True, related_name='enrollments', through='users.Rel_Enrollment_Lesson', to='courses.lesson'),
        ),
    ]
