# Generated by Django 4.1.1 on 2022-10-18 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_course_title'),
        ('users', '0016_rel_enrollment_lesson_enrollment_completelessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rel_Enrollment_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.enrollment')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.material')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'db_table': '_enrollment_material_',
            },
        ),
    ]
