# Generated by Django 4.1.1 on 2022-10-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_course_title'),
        ('users', '0017_rel_enrollment_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completeMaterials',
            field=models.ManyToManyField(blank=True, related_name='enrollments', through='users.Rel_Enrollment_Material', to='courses.material'),
        ),
    ]
