# Generated by Django 4.1.1 on 2022-10-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_course_title'),
        ('users', '0018_enrollment_completematerials'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rel_enrollment_lesson',
            unique_together={('enrollment', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='rel_enrollment_material',
            unique_together={('enrollment', 'material')},
        ),
    ]
