# Generated by Django 4.1.1 on 2022-10-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_rel_enrollment_lesson_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rel_enrollment_lesson',
            options={'verbose_name': 'Complete Lesson', 'verbose_name_plural': 'Complete Lessons'},
        ),
        migrations.AlterModelOptions(
            name='rel_enrollment_material',
            options={'verbose_name': 'Complete Material', 'verbose_name_plural': 'Complete Materials'},
        ),
    ]
