# Generated by Django 4.1.1 on 2022-10-28 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_rel_enrollment_lesson_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rel_Enrollment_Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='users.enrollment')),
                ('lesson', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('result', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'db_table': '_enrollment_lesson_',
            },
        ),
    ]
