# Generated by Django 4.1.1 on 2022-10-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_alter_question_exam_and_more'),
        ('users', '0023_rel_enrollment_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rel_enrollment_lesson',
            options={'verbose_name': 'Complete Lesson', 'verbose_name_plural': 'Complete Lessons'},
        ),
        migrations.AlterField(
            model_name='rel_enrollment_lesson',
            name='result',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rel_enrollment_lesson',
            unique_together={('enrollment', 'lesson')},
        ),
    ]
