# Generated by Django 4.1.1 on 2022-10-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_alter_question_exam_and_more'),
        ('users', '0024_alter_rel_enrollment_lesson_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rel_Enrollment_Lesson',
            new_name='CompleteLesson',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='completeLessons',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='completeMaterials',
        ),
        migrations.DeleteModel(
            name='Rel_Enrollment_Material',
        ),
    ]
