# Generated by Django 4.1.1 on 2022-11-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
