# Generated by Django 4.1.1 on 2022-11-03 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_enrollment_iscomplete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='isComplete',
        ),
    ]
