# Generated by Django 4.1.1 on 2022-11-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='issued_at',
            new_name='date',
        ),
    ]
