# Generated by Django 4.1.1 on 2022-12-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_documentbookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imageUrl',
            field=models.ImageField(blank=True, default=None, max_length=255, null=True, upload_to='uploads/profile_images/'),
        ),
    ]
